### ISSUE TITLE
Can this plug-in be used to securely store a password within a {NS} app?

### ISSUE THREAD

**Issue by erjdriver** [nabil-mansouri/nativescript-bcryptjs#1]
Can this plug-in be used to securely store a password within a {NS} app?

I'd like to store a user password - but it has to be secure.

Can that be done with this app?

If so, can you please provide some detailed documentation.

I apologize - this isn't an "issue" but didn't know how else to contact you.

**Comment by nabil-mansouri** [comment]
Hi guy!
I think that it is a strong algorythm encryption for NS apps.
I think there is no matter to use it storing passords.
My plugin is based on this plugin : https://github.com/dcodeIO/bcrypt.js
Instead of including NPM dependency I imported javascript file directly inside my plugin because of some issues for compiling in android.
Please feel free to close issue if it ok for you!
